import { Hsluv } from "hsluv";

export interface PaletteConfig {
  saturation: number;
  hueRange: [number, number];
  hueSteps: number;
  luminanceRange: [number, number];
  luminanceSteps: number;
}

export interface ColorCell {
  hex: string;
  hue: number;
  saturation: number;
  luminance: number;
  columnId: string;
  cellId: string;
}

export const defaultConfig: PaletteConfig = {
  hueRange: [0, 360],
  hueSteps: 12,
  luminanceRange: [15, 85],
  luminanceSteps: 9,
  saturation: 80,
};

export function generatePalette(config: PaletteConfig): ColorCell[][] {
  const { saturation, hueRange, hueSteps, luminanceRange, luminanceSteps } =
    config;
  const safeHueRange: [number, number] = [
    hueRange[0],
    hueRange[1] === 360 ? 359.999 : hueRange[1],
  ];
  const palette: ColorCell[][] = [];

  for (let h = 0; h < hueSteps; h++) {
    const column: ColorCell[] = [];
    const hueIncrement =
      hueSteps > 1 ? (safeHueRange[1] - safeHueRange[0]) / (hueSteps - 1) : 0;
    const hue = (safeHueRange[0] + hueIncrement * h) % 360;

    for (let l = 0; l < luminanceSteps; l++) {
      const lumIncrement =
        luminanceSteps > 1
          ? (luminanceRange[1] - luminanceRange[0]) / (luminanceSteps - 1)
          : 0;
      const luminance = luminanceRange[0] + lumIncrement * l;

      const color = new Hsluv();
      color.hsluv_h = hue;
      color.hsluv_s = saturation;
      color.hsluv_l = luminance;
      color.hsluvToHex();

      column.push({
        cellId: `cell-${h}-${l}`,
        columnId: `col-${h}`,
        hex: color.hex,
        hue,
        luminance,
        saturation,
      });
    }
    palette.push(column);
  }

  return palette;
}

export interface ShaddercnTokens {
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  muted: string;
  mutedForeground: string;
  destructive: string;
  destructiveForeground: string;
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  border: string;
  input: string;
  ring: string;
}

export const defaultTokens: ShaddercnTokens = {
  accent: "#f59e0b",
  accentForeground: "#000000",
  background: "#ffffff",
  border: "#e5e7eb",
  card: "#ffffff",
  cardForeground: "#0a0a0a",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  foreground: "#0a0a0a",
  input: "#e5e7eb",
  muted: "#f3f4f6",
  mutedForeground: "#6b7280",
  popover: "#ffffff",
  popoverForeground: "#0a0a0a",
  primary: "#0066cc",
  primaryForeground: "#ffffff",
  ring: "#0066cc",
  secondary: "#6b7280",
  secondaryForeground: "#ffffff",
};

export function generateCSSVariables(
  tokens: ShaddercnTokens,
  isDark: boolean,
): string {
  const selector = isDark ? ".dark" : ":root";

  return `${selector} {
  --background: ${tokens.background};
  --foreground: ${tokens.foreground};
  --card: ${tokens.card};
  --card-foreground: ${tokens.cardForeground};
  --popover: ${tokens.popover};
  --popover-foreground: ${tokens.popoverForeground};
  --primary: ${tokens.primary};
  --primary-foreground: ${tokens.primaryForeground};
  --secondary: ${tokens.secondary};
  --secondary-foreground: ${tokens.secondaryForeground};
  --muted: ${tokens.muted};
  --muted-foreground: ${tokens.mutedForeground};
  --accent: ${tokens.accent};
  --accent-foreground: ${tokens.accentForeground};
  --destructive: ${tokens.destructive};
  --destructive-foreground: ${tokens.destructiveForeground};
  --border: ${tokens.border};
  --input: ${tokens.input};
  --ring: ${tokens.ring};
}`;
}

export function downloadCSS(tokens: ShaddercnTokens): void {
  const lightCSS = generateCSSVariables(tokens, false);
  const darkTokens = generateDarkTokens(tokens);
  const darkCSS = generateCSSVariables(darkTokens, true);

  const fullCSS = `/* Generated by Shaddercn Palette Tool */

${lightCSS}

${darkCSS}
`;

  const blob = new Blob([fullCSS], { type: "text/css" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "shaddercn-palette.css";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function generateDarkTokens(lightTokens: ShaddercnTokens): ShaddercnTokens {
  // Simple inversion for dark mode - swap light/dark values
  return {
    ...lightTokens,
    background: lightTokens.foreground,
    border: "#27272a",
    card: lightTokens.foreground,
    cardForeground: lightTokens.background,
    foreground: lightTokens.background,
    input: "#27272a",
    muted: "#27272a",
    mutedForeground: "#a1a1aa",
    popover: lightTokens.foreground,
    popoverForeground: lightTokens.background,
  };
}
